### PR TITLE
Allow upload of multiple DBs

### PR DESCRIPTION
**Pull request by pezholio**
This may be a misuse of `ENV`, but it means that we can specify different DBs in our shared env, and also multiple databases can be uploaded at any one time

### CODE REVIEW

**Comment by pikesley** [comment]
I don't think .env is the right place for this

**Comment by pezholio** [comment]
OK, so we can do a `show databases;` query, but the databases would need to be viewable by everyone, otherwise we'd need to be putting authentication stuff in the env, which would screw things up for Chef.

**Comment by pikesley** [comment]
I think I know how to do this. Cannot brain sufficiently now, but this is a solved problem (see e.g. https://github.com/pikesley/backup_scripts)

**Comment by pezholio** [comment]
Summat like that? ^

**Pull request merged**
