### PR TITLE
Write tests

### PR DESCRIPTION
**Pull request by pezholio**
Opening PR for discussion. The backup test passes fine, but the restore one craps out on the second database - I get a bzcat error:

```
bzcat: Compressed file ends unexpectedly;
perhaps it is corrupted?  *Possible* reason follows.
bzcat: Undefined error: 0
Input file = /var/folders/fd/lbnwy8051t52d_ry5_gwhc0r0000gn/T/20130516-10609-1p66a4e, output file = (stdout)
```

If I comment out the line that unlinks the downloaded file and try the command manually, everything works as expected. WAT.

I have a feature for the `cleanup` command, but haven't even started on that yet.

### CODE REVIEW

**Comment by pezholio** [comment]
This is ready for merge now

**Comment by pikesley** [comment]
Oh, we _really_ broke something here. On a live node:

```
hoppler@mysql-certificate-theodi-org:~/hoppler$ rake hoppler:backup
Installing apt (1.9.2)
Installing build-essential (1.4.0)
Installing openssl (1.0.2)
Installing mysql (3.0.0)
sh: 1: vagrant: not found
rake aborted!
Access denied for user 'root'@'localhost' (using password: NO)
/home/hoppler/.rvm/gems/ruby-2.0.0-p0@hoppler/gems/mysql2-0.3.11/lib/mysql2/client.rb:44:in `connect'
/home/hoppler/.rvm/gems/ruby-2.0.0-p0@hoppler/gems/mysql2-0.3.11/lib/mysql2/client.rb:44:in `initialize'
/home/hoppler/hoppler/lib/hoppler.rb:130:in `new'
/home/hoppler/hoppler/lib/hoppler.rb:130:in `connection'
/home/hoppler/hoppler/lib/hoppler.rb:38:in `backup'
/home/hoppler/hoppler/Rakefile:12:in `block (2 levels) in <top (required)>'
/home/hoppler/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/task.rb:246:in `call'
/home/hoppler/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/task.rb:246:in `block in execute'
/home/hoppler/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/task.rb:241:in `each'
/home/hoppler/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
/home/hoppler/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/task.rb:184:in `block in invoke_with_call_chain'
/home/hoppler/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/home/hoppler/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/task.rb:170:in `invoke'
/home/hoppler/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
/home/hoppler/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/home/hoppler/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/application.rb:101:in `each'
/home/hoppler/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/application.rb:101:in `block in top_level'
/home/hoppler/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/application.rb:110:in `run_with_threads'
/home/hoppler/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/application.rb:95:in `top_level'
/home/hoppler/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/application.rb:73:in `block in run'
/home/hoppler/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/home/hoppler/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
/home/hoppler/.rvm/gems/ruby-2.0.0-p0@hoppler/bin/ruby_noexec_wrapper:14:in `eval'
/home/hoppler/.rvm/gems/ruby-2.0.0-p0@hoppler/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => hoppler:backup
(See full trace by running task with --trace)
hoppler@mysql-certificate-theodi-org:~/hoppler$
```

**Comment by JeniT** [comment]
perfect discovery at 17:30 on a Friday

**Comment by pezholio** [comment]
Is this a `.env` thing? I think the credentials are loaded in from `.env` now, not `mysql.env`, which may be the issue.

**Pull request merged**
