### PR TITLE
Backup all local databases

### PR DESCRIPTION
**Pull request by Floppy**

### CODE REVIEW

**Comment by Floppy** [comment]
Something is wrong here, this code is not as it should be. Let me review - possible bad merge.

**Comment by Floppy** [comment]
the merge is fine, but there's some strangeness in the previous commits. Review the complete diff instead of commit-by-commit, something's a little screwy in there.

**Comment by pezholio** [comment]
Ah, OK. Looks good then. My only two concerns are the stuff with chef and data bags and also how safe is it to be specifying the password directly on the command line? I included the `~/.my.cnf` step to get around that, but I might be being overcautious.

**Comment by Floppy** [comment]
so the theory is that chef can make the .mysql.env quite easily (which is why it is separate). Although; did your .my.cnf get read when making the Ruby-level connection as well? I couldn't tell if that would work (which is why I changed it).

**Comment by Floppy** [comment]
just added a filter to the file removal part

**Comment by Floppy** [comment]
no, ruby client won't load from .my.cnf, so I'm happy with this as it is.

**Comment by pezholio** [comment]
Ditto - meant to say I'd already tried it - soz!

**Pull request merged**
